#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * Writes api/env.local.php from environment variables.
 * For GitHub Actions: pass secrets as env, run this step before SFTP deploy to IONOS.
 * Do not run before publishing to GitHub Pages (secrets would be in the published tree).
 */

$root = dirname(__DIR__);
$target = $root . '/api/env.local.php';

$login = trim((string) getenv('ADMIN_LOGIN'));
$password = (string) getenv('ADMIN_PASSWORD');

if ($login === '' || $password === '') {
    fwrite(STDERR, "ADMIN_LOGIN and ADMIN_PASSWORD must be set in the environment.\n");
    exit(1);
}

$export = "<?php\n"
    . "declare(strict_types=1);\n\n"
    . "// Generated by scripts/generate-admin-env.php — do not commit.\n"
    . "return [\n"
    . "    'ADMIN_LOGIN' => " . var_export($login, true) . ",\n"
    . "    'ADMIN_PASSWORD' => " . var_export($password, true) . ",\n"
    . "];\n";

if (file_put_contents($target, $export) === false) {
    fwrite(STDERR, "Failed to write {$target}\n");
    exit(1);
}

echo "Wrote {$target}\n";
